### ISSUE TITLE
Application error happens when I submit subscription form.

### ISSUE THREAD

**Issue by daheejo** [sakshamgurung/recodebrain-frontend#1]
Hi sakshamgurung,
I found your website recode brain googling and I like your post so would like to subscribe your website.
But when I click the subscription button filling out the form, some error happens like below.
Just would like to tell you about this. 

![image](https://github.com/sakshamgurung/recodebrain-frontend/assets/74031552/b1ab7f03-fbda-4208-a5ee-cfd061ec6f5e)

Hope you fix it well!

**Comment by sakshamgurung** [comment]
Thanks, @daheejo for reading my blog. Right now, I am occupied with other work. But I will soon look for the issue👍.
